### ISSUE TITLE
`isGlob('?')` returns false

### ISSUE THREAD

**Issue by tgrajewski** [micromatch/is-glob#13]
I've noticed that `isGlob()` returns `false` when called with simple patterns with only question mark in them. Is this intended?

```javascript
isGlob('*');  // true
isGlob('?');  // false
isGlob('audio/?.m4a');  // false again
```

**Comment by jonschlinkert** [comment]
I get the following: 

```js
console.log(isGlob('*')) // true
console.log(isGlob('?', { strict: false })) // false
console.log(isGlob('audio/?.m4a', { strict: false })) // false
```

**Comment by WORMSS** [comment]
Hello, I am trying to match 
```
abc/a.ts
abc/b.ts
abc/c.ts
```
so I wrote
```
isGlob('abc/?.ts') // false
```
But `isGlob('abc/?.ts')` should return true.. Right?

> https://en.wikipedia.org/wiki/Glob_(programming)
> The other common wildcard is the question mark (?), which stands for one character.

I had to do `{ strict: false }` which makes me uneasy..
