### ISSUE TITLE
not working for path with backslashes

### ISSUE THREAD

**Issue by MhMadHamster** [micromatch/is-glob#9]
Hey, i have a question about backslashes, now it's not working for path with just backslashes: `path\with\glob\*` , it is, though, working for escaped one: `path\\with\\glob\\*`. It was working for single backslashes in version 2, so the question is: Is this intended behavior or not?
Thanks.

**Comment by es128** [comment]
It is intended because backslashes are not valid path separators for globs, regardless of platform. This lib is more sophisticated and accurate than it was in earlier versions.

Backslashes are needed for escaping, hence `\\*` means you intend for there to be a literal asterisk in the path name.
